febraban_occurrences = {
    "00": "Crédito ou Débito Efetivado - Este código indica que o pagamento foi confirmado",
    "01": "Insuficiência de Fundos - Débito Não Efetuado",
    "02": "Crédito ou Débito Cancelado pelo Pagador/Credor",
    "03": "Débito Autorizado pela Agência - Efetuado",
    "AA": "Controle Inválido",
    "AB": "Tipo de Operação Inválido",
    "AC": "Tipo de Serviço Inválido",
    "AD": "Forma de Lançamento Inválida",
    "AE": "Tipo/Número de Inscrição Inválido",
    "AF": "Código de Convênio Inválido",
    "AG": "Agência/Conta Corrente/DV Inválido",
    "AH": "Nº Seqüencial do Registro no Lote Inválido",
    "AI": "Código de Segmento de Detalhe Inválido",
    "AJ": "Tipo de Movimento Inválido",
    "AK": "Código da Câmara de Compensação do Banco Favorecido/Depositário Inválido",
    "AL": "Código do Banco Favorecido, Instituição de Pagamento ou Depositário Inválido",
    "AM": "Agência Mantenedora da Conta Corrente do Favorecido Inválida",
    "AN": "Conta Corrente/DV/Conta de Pagamento do Favorecido Inválido",
    "AO": "Nome do Favorecido Não Informado",
    "AP": "Data Lançamento Inválido",
    "AQ": "Tipo/Quantidade da Moeda Inválido",
    "AR": "Valor do Lançamento Inválido",
    "AS": "Aviso ao Favorecido - Identificação Inválida",
    "AT": "Tipo/Número de Inscrição do Favorecido Inválido",
    "AU": "Logradouro do Favorecido Não Informado",
    "AV": "Nº do Local do Favorecido Não Informado",
    "AW": "Cidade do Favorecido Não Informada",
    "AX": "CEP/Complemento do Favorecido Inválido",
    "AY": "Sigla do Estado do Favorecido Inválida",
    "AZ": "Código/Nome do Banco Depositário Inválido",
    "BA": "Código/Nome da Agência Depositária Não Informado",
    "BB": "Seu Número Inválido",
    "BC": "Nosso Número Inválido",
    "BD": "Inclusão Efetuada com Sucesso",
    "BE": "Alteração Efetuada com Sucesso",
    "BF": "Exclusão Efetuada com Sucesso",
    "BG": "Agência/Conta Impedida Legalmente",
    "BH": "Empresa não pagou salário",
    "BI": "Falecimento do mutuário",
    "BJ": "Empresa não enviou remessa do mutuário",
    "BK": "Empresa não enviou remessa no vencimento",
    "BL": "Valor da parcela inválida",
    "BM": "Identificação do contrato inválida",
    "BN": "Operação de Consignação Incluída com Sucesso",
    "BO": "Operação de Consignação Alterada com Sucesso",
    "BP": "Operação de Consignação Excluída com Sucesso",
    "BQ": "Operação de Consignação Liquidada com Sucesso",
    "BR": "Reativação Efetuada com Sucesso",
    "BS": "Suspensão Efetuada com Sucesso",
    "CA": "Código de Barras - Código do Banco Inválido",
    "CB": "Código de Barras - Código da Moeda Inválido",
    "CC": "Código de Barras - Dígito Verificador Geral Inválido",
    "CD": "Código de Barras - Valor do Título Inválido",
    "CE": "Código de Barras - Campo Livre Inválido",
    "CF": "Valor do Documento Inválido",
    "CG": "Valor do Abatimento Inválido",
    "CH": "Valor do Desconto Inválido",
    "CI": "Valor de Mora Inválido",
    "CJ": "Valor da Multa Inválido",
    "CK": "Valor do IR Inválido",
    "CL": "Valor do ISS Inválido",
    "CM": "Valor do IOF Inválido",
    "CN": "Valor de Outras Deduções Inválido",
    "CO": "Valor de Outros Acréscimos Inválido",
    "CP": "Valor do INSS Inválido",
    "HA": "Lote Não Aceito",
    "HB": "Inscrição da Empresa Inválida para o Contrato",
    "HC": "Convênio com a Empresa Inexistente/Inválido para o Contrato",
    "HD": "Agência/Conta Corrente da Empresa Inexistente/Inválido para o Contrato",
    "HE": "Tipo de Serviço Inválido para o Contrato",
    "HF": "Conta Corrente da Empresa com Saldo Insuficiente",
    "HG": "Lote de Serviço Fora de Seqüência",
    "HH": "Lote de Serviço Inválido",
    "HI": "Arquivo não aceito",
    "HJ": "Tipo de Registro Inválido",
    "HK": "Código Remessa / Retorno Inválido",
    "HL": "Versão de layout inválida",
    "HM": "Mutuário não identificado",
    "HN": "Tipo do beneficio não permite empréstimo",
    "HO": "Beneficio cessado/suspenso",
    "HP": "Beneficio possui representante legal",
    "HQ": "Beneficio é do tipo PA (Pensão alimentícia)",
    "HR": "Quantidade de contratos permitida excedida",
    "HS": "Beneficio não pertence ao Banco informado",
    "HT": "Início do desconto informado já ultrapassado",
    "HU": "Número da parcela inválida",
    "HV": "Quantidade de parcela inválida",
    "HW": "Margem consignável excedida para o mutuário dentro do prazo do contrato",
    "HX": "Empréstimo já cadastrado",
    "HY": "Empréstimo inexistente",
    "HZ": "Empréstimo já encerrado",
    "H1": "Arquivo sem trailer",
    "H2": "Mutuário sem crédito na competência",
    "H3": "Não descontado – outros motivos",
    "H4": "Retorno de Crédito não pago",
    "H5": "Cancelamento de empréstimo retroativo",
    "H6": "Outros Motivos de Glosa",
    "H7": "Margem consignável excedida para o mutuário acima do prazo do contrato",
    "H8": "Mutuário desligado do empregador",
    "H9": "Mutuário afastado por licença",
    "IA": "Primeiro nome do mutuário diferente do primeiro nome do movimento do censo ou diferente da base de Titular do Benefício",
    "IB": "Benefício suspenso/cessado pela APS ou Sisobi",
    "IC": "Benefício suspenso por dependência de cálculo",
    "ID": "Benefício suspenso/cessado pela inspetoria/auditoria",
    "IE": "Benefício bloqueado para empréstimo pelo beneficiário",
    "IF": "Benefício bloqueado para empréstimo por TBM",
    "IG": "Benefício está em fase de concessão de PA ou desdobramento",
    "IH": "Benefício cessado por óbito",
    "II": "Benefício cessado por fraude",
    "IJ": "Benefício cessado por concessão de outro benefício",
    "IK": "Benefício cessado: estatutário transferido para órgão de origem",
    "IL": "Empréstimo suspenso pela APS",
    "IM": "Empréstimo cancelado pelo banco",
    "IN": "Crédito transformado em PAB",
    "IO": "Término da consignação foi alterado",
    "IP": "Fim do empréstimo ocorreu durante período de suspensão ou concessão",
    "IQ": "Empréstimo suspenso pelo banco",
    "IR": "Não averbação de contrato – quantidade de parcelas/competências informadas ultrapassou a data limite da extinção de cota do dependente titular de benefícios",
    "TA": "Lote Não Aceito - Totais do Lote com Diferença",
    "YA": "Título Não Encontrado",
    "YB": "Identificador Registro Opcional Inválido",
    "YC": "Código Padrão Inválido",
    "YD": "Código de Ocorrência Inválido",
    "YE": "Complemento de Ocorrência Inválido",
    "YF": "Alegação já Informada",
    "ZA": "Agência / Conta do Favorecido Substituída",
    "ZB": "Divergência entre o primeiro e último nome do beneficiário versus primeiro e último nome na Receita Federal",
    "ZC": "Confirmação de Antecipação de Valor",
    "ZD": "Antecipação parcial de valor",
    "ZE": "Título bloqueado na base",
    "ZF": "Sistema em contingência – título valor maior que referência",
    "ZG": "Sistema em contingência – título vencido",
    "ZH": "Sistema em contingência – título indexado",
    "ZI": "Beneficiário divergente",
    "ZJ": "Limite de pagamentos parciais excedido",
    "ZK": "Boleto já liquidado",

}
# Observação: As ocorrências iniciadas com "ZA" tem caráter informativo para o cliente

itau_occurrences = {
    "00": "Pagamento Efetuado",
    "AE": "DATA DE PAGAMENTO ALTERADA",
    "AG": "NÚMERO DO LOTE INVÁLIDO",
    "AH": "NÚMERO SEQUENCIAL DO REGISTRO NO LOTE INVÁLIDO",
    "AI": "PRODUTO DEMONSTRATIVO DE PAGAMENTO NÃO CONTRATADO",
    "AJ": "TIPO DE MOVIMENTO INVÁLIDO",
    "AL": "CÓDIGO DO BANCO FAVORECIDO INVÁLIDO",
    "AM": "AGÊNCIA DO FAVORECIDO INVÁLIDA",
    "AN": "CONTA CORRENTE DO FAVORECIDO INVÁLIDA / CONTA INVESTIMENTO EXTINTA EM 30/04/2011",
    "AO": "NOME DO FAVORECIDO INVÁLIDO",
    "AP": "DATA DE PAGAMENTO / DATA DE VALIDADE / HORA DE LANÇAMENTO /ARRECADAÇÃO / APURAÇÃO INVÁLIDA",
    "AQ": "QUANTIDADE DE REGISTROS MAIOR QUE 999999",
    "AR": "VALOR ARRECADADO / LANÇAMENTO INVÁLIDO",
    "BC": "NOSSO NÚMERO INVÁLIDO",
    "BD": "Pagamento Agendado",
    "BE": "Pagamento AGENDADO COM FORMA ALTEARADA PARA OP",
    "BI": "CNPJ/CPF DO BENEFICIÁRIO INVÁLIDO NO SEGMENTO J-52 ou B INVÁLIDO",
    "BL": "VALOR DA PARCELA INVÁLIDO",
    "CD": "CNPJ / CPF INFORMADO DIVERGENTE DO CADASTRADO",
    "CE": "Pagamento CANCELADO",
    "CF": "VALOR DO DOCUMENTO INVÁLIDO",
    "CG": "VALOR DO ABATIMENTO INVÁLIDO",
    "CH": "VALOR DO DESCONTO INVÁLIDO",
    "CI": "CNPJ / CPF / IDENTIFICADOR / INSCRIÇÃO ESTADUAL / INSCRIÇÃO NO CAD / ICMS INVÁLIDO",
    "CJ": "VALOR DA MULTA INVÁLIDO",
    "CK": "TIPO DE INSCRIÇÃO INVÁLIDA",
    "CL": "VALOR DO INSS INVÁLIDO",
    "CM": "VALOR DO COFINS INVÁLIDO",
    "CN": "CONTA NÃO CADASTRADA",
    "CO": "VALOR DE OUTRAS ENTIDADES INVÁLIDO",
    "CP": "CONFIRMAÇÃO DE OP CUMPRIDA",
    "CQ": "SOMA DAS FATURAS DIFERE DO Pagamento",
    "CR": "VALOR DO CSLL INVÁLIDO",
    "CS": "DATA DE VENCIMENTO DA FATURA INVÁLIDA",
    "DA": "NÚMERO DE DEPEND. SALÁRIO FAMILIA INVALIDO",
    "DB": "NÚMERO DE HORAS SEMANAIS INVÁLIDO",
    "DC": "SALÁRIO DE CONTRIBUIÇÃO INSS INVÁLIDO",
    "DD": "SALÁRIO DE CONTRIBUIÇÃO FGTS INVÁLIDO",
    "DE": "VALOR TOTAL DOS PROVENTOS INVÁLIDO",
    "DF": "VALOR TOTAL DOS DESCONTOS INVÁLIDO",
    "DG": "VALOR LÍQUIDO NÃO NUMÉRICO",
    "DH": "VALOR LIQ. INFORMADO DIFERE DO CALCULADO",
    "DI": "VALOR DO SALÁRIO-BASE INVÁLIDO",
    "DJ": "BASE DE CÁLCULO IRRF INVÁLIDA",
    "DK": "BASE DE CÁLCULO FGTS INVÁLIDA",
    "DL": "FORMA DE Pagamento INCOMPATÍVEL COM HOLERITE",
    "DM": "E-MAIL DO FAVORECIDO INVÁLIDO",
    "DV": "DOC / TED DEVOLVIDO PELO BANCO FAVORECIDO",
    "D0": "FINALIDADE DO HOLERITE INVÁLIDA",
    "D1": "MÊS DE COMPETENCIA DO HOLERITE INVÁLIDA",
    "D2": "DIA DA COMPETENCIA DO HOLETITE INVÁLIDA",
    "D3": "CENTRO DE CUSTO INVÁLIDO",
    "D4": "CAMPO NUMÉRICO DA FUNCIONAL INVÁLIDO",
    "D5": "DATA INÍCIO DE FÉRIAS NÃO NUMÉRICA",
    "D6": "DATA INÍCIO DE FÉRIAS INCONSISTENTE",
    "D7": "DATA FIM DE FÉRIAS NÃO NUMÉRICO",
    "D8": "DATA FIM DE FÉRIAS INCONSISTENTE",
    "D9": "NÚMERO DE DEPENDENTES IR INVÁLIDO",
    "EM": "CONFIRMAÇÃO DE OP EMITIDA",
    "EX": "DEVOLUÇÃO DE OP NÃO SACADA PELO FAVORECIDO",
    "E0": "TIPO DE MOVIMENTO HOLERITE INVÁLIDO",
    "E1": "VALOR 01 DO HOLERITE / INFORME INVÁLIDO",
    "E2": "VALOR 02 DO HOLERITE / INFORME INVÁLIDO",
    "E3": "VALOR 03 DO HOLERITE / INFORME INVÁLIDO",
    "E4": "VALOR 04 DO HOLERITE / INFORME INVÁLIDO",
    "FC": "Pagamento EFETUADO ATRAVÉS DE FINANCIAMENTO COMPROR",
    "FD": "Pagamento EFETUADO ATRAVÉS DE FINANCIAMENTO DESCOMPROR",
    "HA": "ERRO NO HEADER DE ARQUIVO",
    "HM": "ERRO NO HEADER DE LOTE",
    "IB": "VALOR E/OU DATA DO DOCUMENTO INVÁLIDO",
    "IC": "VALOR DO ABATIMENTO INVÁLIDO",
    "ID": "VALOR DO DESCONTO INVÁLIDO",
    "IE": "VALOR DA MORA INVÁLIDO",
    "IF": "VALOR DA MULTA INVÁLIDO",
    "IG": "VALOR DA DEDUÇÃO INVÁLIDO",
    "IH": "VALOR DO ACRÉSCIMO INVÁLIDO",
    "II": "DATA DE VENCIMENTO INVÁLIDA",
    "IJ": "COMPETÊNCIA / PERÍODO REFERÊNCIA / PARCELA INVÁLIDA",
    "IK": "TRIBUTO NÃO LIQUIDÁVEL VIA SISPAG OU NÃO CONVENIADO COM ITAÚ",
    "IL": "CÓDIGO DE Pagamento / EMPRESA /RECEITA INVÁLIDO",
    "IM": "TIPO X FORMA NÃO COMPATÍVEL",
    "IN": "BANCO/AGENCIA NÃO CADASTRADOS",
    "IO": "DAC / VALOR / COMPETÊNCIA / IDENTIFICADOR DO LACRE INVÁLIDO",
    "IP": "DAC DO CÓDIGO DE BARRAS INVÁLIDO",
    "IQ": "DÍVIDA ATIVA OU NÚMERO DE ETIQUETA INVÁLIDO",
    "IR": "Pagamento ALTERADO",
    "IS": "CONCESSIONÁRIA NÃO CONVENIADA COM ITAÚ",
    "IT": "VALOR DO TRIBUTO INVÁLIDO",
    "IU": "VALOR DA RECEITA BRUTA ACUMULADA INVÁLIDO",
    "IV": "NÚMERO DO DOCUMENTO ORIGEM / REFERÊNCIA INVÁLIDO",
    "IX": "CÓDIGO DO PRODUTO INVÁLIDO",
    "LA": "DATA DE Pagamento DE UM LOTE ALTERADA",
    "LC": "LOTE DE PagamentoS CANCELADO",
    "NA": "Pagamento CANCELADO POR FALTA DE AUTORIZAÇÃO",
    "NB": "IDENTIFICAÇÃO DO TRIBUTO INVÁLIDA",
    "NC": "EXERCÍCIO (ANO BASE) INVÁLIDO",
    "ND": "CÓDIGO RENAVAM NÃO ENCONTRADO/INVÁLIDO",
    "NE": "UF INVÁLIDA",
    "NF": "CÓDIGO DO MUNICÍPIO INVÁLIDO",
    "NG": "PLACA INVÁLIDA",
    "NH": "OPÇÃO/PARCELA DE Pagamento INVÁLIDA",
    "NI": "TRIBUTO JÁ FOI PAGO OU ESTÁ VENCIDO",
    "NR": "OPERAÇÃO NÃO REALIZADA",
    "PD": "AQUISIÇÃO CONFIRMADA (EQUIVALE A OCORRÊNCIA 02 NO LAYOUT DE RISCO SACADO)",
    "RJ": "REGISTRO REJEITADO",
    "RS": "Pagamento DISPONÍVEL PARA ANTECIPAÇÃO NO RISCO SACADO – MODALIDADE RISCO SACADO PÓS AUTORIZADO",
    "SS": "Pagamento CANCELADO POR INSUFICIÊNCIA DE SALDO/LIMITE DIÁRIO DE PAGTO",
    "TA": "LOTE NÃO ACEITO - TOTAIS DO LOTE COM DIFERENÇA",
    "TI": "TITULARIDADE INVÁLIDA",
    "X1": "FORMA INCOMPATÍVEL COM LAYOUT 010",
    "X2": "NÚMERO DA NOTA FISCAL INVÁLIDO",
    "X3": "IDENTIFICADOR DE NF/CNPJ INVÁLIDO",
    "X4": "FORMA 32 INVÁLIDA"
}

bradesco_ocorrencias = {
    "00": "Crédito ou Débito Efetivado - Este código indica que o pagamento foi confirmado",
    "01": "Insuficiência de Fundos - Débito Não Efetuado",
    "02": "Crédito ou Débito Cancelado pelo Pagador/Credor",
    "03": "Débito Autorizado pela Agência - Efetuado",
    "AA": "Controle Inválido",
    "AB": "Tipo de Operação Inválido",
    "AC": "Tipo de Serviço Inválido",
    "AD": "Forma de Lançamento Inválida",
    "AE": "Tipo/Número de Inscrição Inválido",
    "AF": "Código de Convênio Inválido",

}